### ISSUE TITLE
Solve python pcl version issue

### ISSUE THREAD

**Issue by santoshreddy254** [santoshreddy254/Data_Augmentor_With_GUI#13]
Python pcl 1.7.2 required

**Comment by santoshreddy254** [comment]
sudo apt-get install libpcl-dev
update numpy>=1.16

**Comment by njanirudh** [comment]
ImportError: libpcl_keypoints.so.1.7: cannot open shared object file: No such file or directory

I tried the above in a new computer still the problem persists
Can you confirm the versions of pcl and numpy this works in

**Comment by santoshreddy254** [comment]
just try unintsalling the python-pcl from pip3. 
Then do the installation of libpcl-dev
upgrade pip and numpy>=1.16
then install python-pcl from pip

please try this and let me know if the problem still exists 
Thank you @njanirudh

**Comment by njanirudh** [comment]
@santoshreddy254 the problem is still there. I am trying to solve it and will let you know.

https://gitmemory.com/issue/strawlab/python-pcl/317/530649238

**Comment by njanirudh** [comment]
The issue in **Ubuntu18.xx** will be due to 
apt installing pcl 1.8
while pip is install the python-pcl which supports only 1.7

So you will have to build libpcl for 1.7 to get it working with python-pcl 

https://github.com/strawlab/python-pcl/issues/306
https://github.com/strawlab/python-pcl/issues/317

**Comment by santoshreddy254** [comment]
Solved for ubuntu 18.04

**Comment by Petros626** [comment]
> Solved for ubuntu 18.04

@ santoshreddy254 can you help me on Ubuntu 20.04?
